"""
VR Tour Builder
───────────────
Run this script whenever you add, remove, or change panorama images.
It reads scenes_config.json and embeds all images into js/scenes.js
as base64 — so the tour works by just opening index.html, no server needed.

Usage:
    python3 build.py

Requirements: Python 3 (no extra libraries needed)

HOW TO ADD A NEW SCENE
───────────────────────
1. Drop your equirectangular panorama PNG into the images/ folder.
2. Open scenes_config.json and add a new entry, e.g.:
      {
        "name": "My New Room",
        "file": "images/my_new_room.png",
        "hotspots": [
          { "targetScene": 0, "label": "Back to Start", "yaw": 180, "pitch": -28 }
        ],
        "assetHotspots": [
          {
            "label": "Hero Asset",
            "title": "Hero Asset",
            "category": "Feature",
            "description": "Brief description shown inside the modal.",
            "yaw": 10,
            "pitch": 6,
            "images": [
              "images/my_asset_render_01.png",
              "images/my_asset_render_02.png"
            ]
          }
        ]
      }
3. Run:  python3 build.py
4. Open index.html in any browser. Done.

HOTSPOT YAW GUIDE
─────────────────
  0   = straight ahead
  90  = to your right
 -90  = to your left
 180  = directly behind you
pitch -28 places the arrow on the ground floor.

To fine-tune positions, open the browser console and run:
    window.DEBUG_YAW = true
Then look around — your current yaw is logged every 0.5 s.
"""

import json, base64, os, sys

CONFIG  = "scenes_config.json"
OUT     = os.path.join("js", "scenes.js")

def encode(path):
    if not os.path.exists(path):
        print(f"  ✗ Missing image: {path}", file=sys.stderr)
        return None
    with open(path, "rb") as f:
        data = base64.b64encode(f.read()).decode()
    ext  = os.path.splitext(path)[1].lstrip(".") or "png"
    mime = "image/jpeg" if ext.lower() in ("jpg", "jpeg") else f"image/{ext.lower()}"
    return f"data:{mime};base64,{data}"

with open(CONFIG, encoding="utf-8") as f:
    scenes = json.load(f)

lines = [
    "// AUTO-GENERATED by build.py — do not edit by hand.",
    "// Edit scenes_config.json + run  python3 build.py  to rebuild.",
    "//",
    "// Images are base64-embedded so the tour works from file:// (no server needed).",
    "",
]

var_names = []
for i, scene in enumerate(scenes):
    var = f"IMG_{i}"
    var_names.append(var)
    path = scene["file"]
    size_kb = os.path.getsize(path) // 1024 if os.path.exists(path) else 0
    print(f"  Embedding scene {i+1}/{len(scenes)}: {path} ({size_kb} KB)")
    data_uri = encode(path)
    if data_uri is None:
        print(f"\n  ERROR: Cannot build — image not found: {path}", file=sys.stderr)
        sys.exit(1)
    lines.append(f"const {var} = '{data_uri}';")
    lines.append("")

lines.append("const SCENES = [")
for i, scene in enumerate(scenes):
    lines.append(f'  {{')
    lines.append(f'    name: "{scene["name"]}",')
    lines.append(f'    file: {var_names[i]},')
    lines.append(f'    hotspots: [')
    for hs in scene.get("hotspots", []):
        lines.append(
            f'      {{ targetScene: {hs["targetScene"]}, label: "{hs["label"]}", '
            f'yaw: {hs["yaw"]}, pitch: {hs["pitch"]} }},'
        )
    lines.append(f'    ]')
    lines.append(f'    ,assetHotspots: [')
    for asset in scene.get("assetHotspots", []):
        image_list = ", ".join(f'"{image}"' for image in asset.get("images", []))
        lines.append(
            '      { '
            f'label: "{asset["label"]}", '
            f'title: "{asset["title"]}", '
            f'category: "{asset.get("category", "")}", '
            f'description: "{asset["description"]}", '
            f'yaw: {asset["yaw"]}, pitch: {asset["pitch"]}, '
            f'images: [{image_list}]'
            ' },'
        )
    lines.append(f'    ]')
    lines.append(f'  }}{"," if i < len(scenes)-1 else ""}')

lines.append("];")
lines.append("")

os.makedirs("js", exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

total_kb = os.path.getsize(OUT) // 1024
print(f"\n  ✓ Built {OUT}  ({total_kb} KB total)")
print(f"  ✓ {len(scenes)} scenes embedded")
print(f"\n  Open index.html in any browser to preview.")
